(SourceTable as table) as table =>
    let
        TypeTransformations = {
            {"Company Code", type text},
            {"Structure", type text},
            {"Semantic Tag", type text},
            {"Signature", type text},
            {"Signature Code", type text},
            {"Signature2", type text},
            {"Accounting doc type", type text},
            {"Fiscal Year", Int64.Type},
            {"Fiscal Period", Int64.Type},
            {"Ledger", type text},
            {"Profit Center", type text},
            {"Profit Center Name", type text},
            {"Distribution Channel", Int64.Type},
            {"Material", type text},
            {"G/L Account", Int64.Type},
            {"G/L Account Name", type text},
            {"G/L Account Type", type text},
            {"Journal Entry Type", type text},
            {"JE Type Name", type text},
            {"Journal Entry Item Text", type text},
            {"Amount in Company Code Currency", Currency.Type},
            {"Purchasing Document", type text},
            {"Purchasing Doc. Item", Int64.Type},
            {"Cost Center", type text},
            {"Cost Center Name", type text},
            {"Partner Cost Center", type text},
            {"Project", type text},
            {"Project Name", type text},
            {"WBS Element External ID", type text},
            {"WBS Element", type text},
            {"WBS Element Name", type text},
            {"Product", type text},
            {"Reference Document Category", type text},
            {"Debit Date", type datetime},
            {"Object Type", type text},
            {"Project definition", type text},
            {"Object", type text},
            {"Cost element", Int64.Type},
            {"Cost element desc.", type text},
            {"Value in Obj. Crcy", type number},
            {"Val.in rep.cur.", type number},
            {"Total Quantity", type number},
            {"Quantity/Plan", type number},
            {"Object Currency", type text},
            {"Unit of Measure", type text},
            {"Value TranCurr", type number},
            {"Val/COArea Crcy", type number},
            {"User Name", type text},
            {"Supplier", type text},
            {"Ref. document number", type text},
            {"Reference Item", Int64.Type},
            {"Reference Doc. Type", type text},
            {"Reference date", type datetime},
            {"Name", type text},
            {"Period", Int64.Type},
            {"Document Date", type datetime},
            {"Business Transaction", type text},
            {"CO Object Name", type text}
        },
        ChangedType = Table.TransformColumnTypes(
            SourceTable, TypeTransformations, [Culture = "en-US", MissingField = MissingField.Ignore]
        )
    in
        ChangedType
